title: "Familie Reimer"
baseURL: "https://reimer.family/"

defaultContentLanguage: de


params:
  env: production

metaDataFormat: yaml
enableEmoji: true
enableRobotsTXT: true

disableKinds:
  - taxonomy

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      table: true
      strikethrough: true
      linkify: true
      taskList: true
      typographer: true
    renderer:
      unsafe: True
  highlight:
    noClasses: false
    style: friendly

sitemap:
  changeFreq: monthly
  priority: 0.5
  filename: sitemap.xml
